% Create definition file for NEURON library.
HeaderFilePath = "bin/nrnmatlab.h";
SourceFilePath = "bin/nrnmatlab.cpp";
StaticLibPath = "bin/libnrniv.a";
HeadersIncludePath = "bin";
clibgen.generateLibraryDefinition(HeaderFilePath, ...
    SupportingSourceFiles=SourceFilePath, ...
    Libraries=StaticLibPath, ...
    OverwriteExistingDefinitionFiles=true, ...
    IncludePath=HeadersIncludePath, ...
    PackageName="neuron", ...
    TreatObjectPointerAsScalar=true, ...
    TreatConstCharPointerAsCString=true);
