% Create definition file for NEURON library.
HeaderFilePath = "bin/nrnmatlab.h";
SourceFilePath = "bin/nrnmatlab.cpp";
StaticLibPath = "bin/libnrniv.a";
LibMexPath = fullfile(matlabroot, "extern", "lib", "win64", "mingw64", "libmex.lib"); % For mexPrintf
HeadersIncludePath = "bin";
clibgen.generateLibraryDefinition(HeaderFilePath, ...
    SupportingSourceFiles=SourceFilePath, ...
    Libraries=[StaticLibPath, LibMexPath], ...
    OverwriteExistingDefinitionFiles=true, ...
    IncludePath=HeadersIncludePath, ...
    PackageName="neuron", ...
    TreatObjectPointerAsScalar=true, ...
    TreatConstCharPointerAsCString=true);
